# Generated by Django 4.2.4 on 2023-08-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division_Name', models.CharField(max_length=100, null=True)),
                ('Department_Name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
