# Generated by Django 4.2.4 on 2023-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_department_options_alter_division_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Id', models.CharField(max_length=100, null=True)),
                ('Staff_Name', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('Division', models.CharField(max_length=100, null=True)),
                ('Unit', models.CharField(max_length=100, null=True)),
                ('Section', models.CharField(max_length=100, null=True)),
                ('Date_First_app', models.CharField(max_length=100, null=True)),
                ('Date_Present_app', models.CharField(max_length=100, null=True)),
                ('Cadre', models.CharField(max_length=100, null=True)),
                ('Rank_position', models.CharField(max_length=100, null=True)),
                ('Gloconraiss', models.CharField(max_length=100, null=True)),
                ('DOB', models.CharField(max_length=100, null=True)),
                ('File_No', models.CharField(max_length=100, null=True)),
                ('Geo_Political_zone', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Local_Gov_Area', models.CharField(max_length=100, null=True)),
                ('IPPS', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Staff List',
            },
        ),
    ]
