# Generated by Django 4.2.4 on 2023-08-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Department',
            new_name='Department_Name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Division',
            new_name='Division_Name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Section',
            new_name='Section_Name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Unit',
            new_name='Unit_Name',
        ),
        migrations.AlterField(
            model_name='staff',
            name='DOB',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Date_First_app',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Date_Present_app',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
