# Generated by Django 4.2.4 on 2023-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_department_staff_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Section_Name',
            field=models.CharField(default='No Section', max_length=100, null=True),
        ),
    ]
