# Generated by Django 4.2.4 on 2023-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
